driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.4
    run_list: apt::default
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: opensuse-13.2
  - name: freebsd-9.3
  - name: freebsd-10.2

suites:
  - name: default
    data_bags_path: "./test/fixtures/data_bags"
    run_list:
      - recipe[users_test::test_home_dir]
  - name: sysadmins
    data_bags_path: "./test/fixtures/data_bags"
    run_list:
      - recipe[users::sysadmins]
